### ISSUE TITLE
公開にあたってLICENSE情報の作成

### ISSUE THREAD

**Issue by ROBO358** [TKYcraft/tsuru-run#3]
適当なLICENSEを設定したい。

**Comment by ROBO358** [comment]
現状、並列作業中の非公開リポジトリと同様にMIT Licenseが適切であると考えています。
なんか適切なものがあれば、コメントください。

**Comment by Hikoneko** [comment]
いろいろLicense見てみたけど、1番責任負わなくて良さそうだから、僕もMIT Licenseでいいんじゃないかと思う。(商用利用OKになるのが嫌とかなら考えなきゃかもだけど…)

**Comment by myosotis-dev** [comment]
MIT賛成(スレチだけどリポジトリ名これでいくのか?

**Comment by ROBO358** [comment]
> スレチだけどリポジトリ名これでいくのか?

特に問題ないので、これでヨシッ!
